### ISSUE TITLE
内网穿透是如何实现的？

### ISSUE THREAD

**Issue by Youngv** [IxsCN/Aria2Gee#1]
虽然知道 frp 有内网穿透的功能，但是需要服务端和客户端配合使用，插件只有一个客户端如何实现的？

**Comment by IxsCN** [comment]
服务端使用的是我的服务器。

**Comment by Youngv** [comment]
现在有个问题是路由上装了一个aria2，然后还跑了一个aria2的web，如何让这个web连上路由上的aria2，而不是我本地的aria2
